[package]
name = "egui-dock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.19.0"
egui_dock = { git="https://github.com/Adanos020/egui_dock", rev="5f6a431" }
